
import Image1 from './Assets/img1.jpg'
import Image2 from './Assets/img2.jpg'
import Image3 from './Assets/image3.jpeg'
import Image4 from './Assets/images4.jpeg'
import Image5 from './Assets/img5.webp'
import p1 from './Assets/p9img.png'
import p2 from './Assets/p2 img.png'
import p3 from './Assets/p5img.png'
import p4 from './Assets/p6img.png'
import p5 from './Assets/p7img.png'
import p6 from './Assets/p8img.png'

export const Details=[

    {
        'id':1,
        'Name':'Surya',
        'Rating':4.5,
        'Riview':'Good experience and fastQuite a good experience and very helpful. Rena walked me through the process and answered all my questions. Would use again in future.',
        'image':Image1,
        'Time':'Just Now',
        'Status':'Pending',
        'pimg':p1,
        'pname':'Fitbit Sense Advanced Smartwatch with Tools fo...',
        'price':25000,
        'order_id':2023,
        'p_s':'Paid',
        'f_s':'Success',
        'd_t':'CashOnDelivery',
        'email':'Sury123@gmail.com',
        'orders':25,
        't_s':'10,000ind',
        'city':'Bengalur',
        'l_s':'20 min ago',
        'l_o':'feb-12 4.30PM',
        'q_y':2,
      
    },
    {
        'id':2,
        'Name':'Prasanna',
        'Rating':1.5,
        'Riview':'Very  bad no establishment fee!Your rates are outstanding compared to all other rates I was quoted. I also wasnt charged an establishment fee because I have my mortgage with you. Fantastic customer service as always!',
        'image':Image2,
        'Time':'05-feb-2024',
        'Status':'Pending',
        'pimg':p2,
        'pname':'iPhone 13 pro max-Pacific Blue-128GB storage',
        'price':100000,
        'order_id':2021,
        'p_s':'Pending',
        'f_s':'Success',
        'd_t':'CashOnDelivery',
        'email':'Prasanna426@gmail.com',
        'orders':95,
        't_s':'5,000ind',
        'city':'Gujarath',
        'l_s':'39 min ago',
        'l_o':'Dec-20 6.10PM',
        'q_y':5,
      
    },
    {
        'id':3,
        'Name':'Anu Dheepthi',
        'Rating':2.5,
        'Riview':' Avarage Expirenceand quick to useThe team was responsive and easy to handle. Made the whole process seamless for me.',
        'image':Image3,
        'Time':'01-feb-2024',
        'Status':'Approved',
        'pimg':p3,
        'pname':'Apple MacBook Pro 13 inch-M1-8/256GB-space',
        'price':50000,
        'order_id':2513,
        'p_s':'Paid',
        'f_s':'Cancled',
        'd_t':'Online Method',
        'email':'Anu12345@gmail.com',
        'orders':55,
        't_s':'34,000ind',
        'city':'Assam',
        'l_s':'1 hour ago',
        'l_o':'Sep-11 10.30AM',
        'q_y':8,
      
    },
    {
        'id':4,
        'Name':'Bhagya',
        'Rating':5,
        'Riview':'Ive been in this loan for many years and I have been coming back over and over again because I appreciate the kindness the people have shown towards me',
        'image':Image4,
        'Time':'26-jan-2024',
        'Status':'Approved',
        'pimg':p4,
        'pname':'	Apple iMac 24" 4K Retina Display M1 8 Core CPU...',
        'price':29999,
        'order_id':2304,
        'p_s':'Failed',
        'f_s':'UnFuFilled',
        'd_t':'Express',
        'email':'Bhagya143@gmail.com',
        'orders':15,
        't_s':'99,999ind',
        'city':'Andra Pradhes',
        'l_s':'10 min ago',
        'l_o':'Jul-18 12.30PM',
        'q_y':1,
    },
    {
        'id':5,
        'Name':'Manjula Sree',
        'Rating':1,
        'Riview':'Very very bad to wored to deal with. I highly recommend loans.com I have been coming back over and over again because I appreciate the kindness the people have shown towards me',
        'image':Image5,
        'Time':'01-jan-2024',
        'Status':'Approved',
        'pimg':p5,
        'pname':'Razer Kraken v3 x Wired 7.1 Surroung Sound Gam...',
        'price':29000,
        'order_id':5032,
        'p_s':'Cancled',
        'f_s':'Ready_Pickup',
        'd_t':'CashOnDelivery',
        'email':'ManjuSree@gmail.com',
        'orders':105,
        't_s':'85000ind',
        'city':'Mumbhai',
        'l_s':'5 day ago',
        'l_o':'Aug-15 11.30AM',
        'q_y':4,
    },
    {
        'id':6,
        'Name':'Amrutha',
        'Rating':3,
        'Riview':'Very very bad to wored to deal with. I highly recommend loans.com I have been coming back over and over again because I appreciate the kindness the people have shown towards me',
        'image':Image2,
        'Time':'01-jan-2024',
        'Status':'Approved',
        'pimg':p6,
        'pname':'	PlayStation 5 DualSense Wireless Controller',
        'price':99999,
        'order_id':1203,
        'p_s':'Pending',
        'f_s':'Success',
        'd_t':'Local Delivery',
        'email':'Amrutha143@gmail.com',
        'orders':75,
        't_s':'60,000ind',
        'city':'Chennai',
        'l_s':'20 day ago',
        'l_o':'Feb-29 1.30PM',
        'q_y':9,
    },
]